name: Docs
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install
        run: yarn install
      - name: Generate docs
        run: yarn run docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
